export { default as CPF } from './CPF'
export { default as Email } from './Email'
export { default as Home } from './Home'
export { default as Name } from './Name'
export { default as Password } from './Password'
export { default as Success } from './Success'
